# Generated by Django 5.2.5 on 2025-09-03 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EBooklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Short description for listing pages')),
                ('abstract', models.TextField(blank=True, help_text='Detailed abstract', null=True)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ebooklets/images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='ebooklets/files/')),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('authors', models.JSONField(default=list, help_text='List of author names')),
                ('target_audience', models.JSONField(default=list, help_text='List of target audiences')),
                ('file_formats', models.JSONField(default=list, help_text='Available file formats')),
                ('table_of_contents', models.JSONField(default=list, help_text='Table of contents items')),
                ('keywords', models.JSONField(default=list, help_text='Keywords for search')),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization')),
                ('pages', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(default='English', max_length=50)),
                ('isbn', models.CharField(blank=True, max_length=17, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EBookletDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ebooklet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='ebooklets.ebooklet')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EBookletView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ebooklet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='ebooklets.ebooklet')),
            ],
            options={
                'unique_together': {('ebooklet', 'ip_address')},
            },
        ),
    ]
