# Generated by Django 5.2.5 on 2025-08-18 23:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('theme', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('full_description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('in_person', 'In Person'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='in_person', max_length=20)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('registration_open', 'Registration Open'), ('coming_soon', 'Coming Soon'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='conference_images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('regular_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('early_bird_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('early_bird_deadline', models.DateField(blank=True, null=True)),
                ('expected_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('countries_represented', models.PositiveIntegerField(blank=True, null=True)),
                ('highlights', models.TextField(blank=True, null=True)),
                ('organizer_name', models.CharField(default='African Child Neurology Association (ACNA)', max_length=200)),
                ('organizer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organizer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('organizer_website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference')),
            ],
            options={
                'verbose_name': 'Conference View',
                'verbose_name_plural': 'Conference Views',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_type', models.CharField(choices=[('early_bird', 'Early Bird'), ('regular', 'Regular'), ('student', 'Student'), ('speaker', 'Speaker'), ('sponsor', 'Sponsor')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dietary_requirements', models.TextField(blank=True, null=True)),
                ('accessibility_needs', models.TextField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='conferences.conference')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('session_type', models.CharField(choices=[('presentation', 'Presentation'), ('workshop', 'Workshop'), ('panel', 'Panel Discussion'), ('keynote', 'Keynote'), ('break', 'Break'), ('registration', 'Registration'), ('social', 'Social Event'), ('networking', 'Networking')], default='presentation', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('speaker_names', models.CharField(blank=True, max_length=300, null=True)),
                ('moderator', models.CharField(blank=True, max_length=200, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('materials_required', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='conferences.conference')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='speaker_images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('expertise', models.TextField(blank=True, null=True)),
                ('is_keynote', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='conferences.conference')),
            ],
        ),
    ]
