# Generated by Django 5.2.5 on 2025-08-18 08:36

import conferences.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('In-person', 'In-person'), ('Virtual', 'Virtual'), ('Hybrid', 'Hybrid')], default='In-person', max_length=20)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Registration Open', 'Registration Open'), ('Coming Soon', 'Coming Soon'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planning', max_length=20)),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=conferences.models.conference_image_path)),
                ('image_url', models.URLField(blank=True, help_text='External image URL or uploaded image path', null=True)),
                ('attendees', models.CharField(blank=True, max_length=20)),
                ('speakers', models.CharField(blank=True, max_length=20)),
                ('countries', models.CharField(blank=True, max_length=20)),
                ('early_bird_deadline', models.DateField(blank=True, null=True)),
                ('regular_fee', models.CharField(blank=True, max_length=50)),
                ('early_bird_fee', models.CharField(blank=True, max_length=50)),
                ('registration_count', models.PositiveIntegerField(default=0)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='conferences.conference')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('registration_type', models.CharField(choices=[('Early Bird', 'Early Bird'), ('Regular', 'Regular')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=20)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='conferences.conference')),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
    ]
