# Generated by Django 5.2.5 on 2025-09-26 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stripe_checkout_session_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_type', models.CharField(choices=[('conference_registration', 'Conference Registration')], default='conference_registration', max_length=30)),
                ('registration_type', models.CharField(choices=[('early_bird', 'Early Bird'), ('regular', 'Regular'), ('student', 'Student'), ('speaker', 'Speaker'), ('sponsor', 'Sponsor')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='conferences.conference')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='conferences.registration')),
            ],
            options={
                'verbose_name': 'Conference Payment',
                'verbose_name_plural': 'Conference Payments',
            },
        ),
    ]
