# Generated by Django 5.2.5 on 2025-09-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_alter_registration_payment_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('conference', 'email')},
        ),
    ]
