# Generated by Django 5.2.5 on 2025-09-24 19:21

import careers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Volunteer', 'Volunteer')], default='Full-time', max_length=20)),
                ('level', models.CharField(choices=[('Entry-level', 'Entry-level'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior'), ('Executive', 'Executive')], default='Mid-level', max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Closed', 'Closed')], default='Draft', max_length=10)),
                ('description', models.TextField()),
                ('salary', models.CharField(max_length=100)),
                ('closing_date', models.DateField()),
                ('contract_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('work_arrangement', models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='On-site', max_length=10)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Opportunity',
                'verbose_name_plural': 'Job Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('availability', models.CharField(max_length=100)),
                ('experience', models.TextField()),
                ('motivation', models.TextField()),
                ('status', models.CharField(choices=[('Pending Review', 'Pending Review'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Pending Review', max_length=20)),
                ('hours_contributed', models.PositiveIntegerField(default=0)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Volunteer Submission',
                'verbose_name_plural': 'Volunteer Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(max_length=500)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='careers.jobopportunity')),
            ],
            options={
                'verbose_name': 'Job Benefit',
                'verbose_name_plural': 'Job Benefits',
                'unique_together': {('job', 'benefit')},
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('New', 'New'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='New', max_length=20)),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(upload_to=careers.models.job_application_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='careers.jobopportunity')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
                'unique_together': {('opportunity', 'email')},
            },
        ),
        migrations.CreateModel(
            name='JobQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=500)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='careers.jobopportunity')),
            ],
            options={
                'verbose_name': 'Job Qualification',
                'verbose_name_plural': 'Job Qualifications',
                'unique_together': {('job', 'qualification')},
            },
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=500)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='careers.jobopportunity')),
            ],
            options={
                'verbose_name': 'Job Requirement',
                'verbose_name_plural': 'Job Requirements',
                'unique_together': {('job', 'requirement')},
            },
        ),
        migrations.CreateModel(
            name='JobResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility', models.CharField(max_length=500)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='careers.jobopportunity')),
            ],
            options={
                'verbose_name': 'Job Responsibility',
                'verbose_name_plural': 'Job Responsibilities',
                'unique_together': {('job', 'responsibility')},
            },
        ),
        migrations.CreateModel(
            name='VolunteerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='careers.volunteersubmission')),
            ],
            options={
                'verbose_name': 'Volunteer Skill',
                'verbose_name_plural': 'Volunteer Skills',
                'unique_together': {('volunteer', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='VolunteerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='careers.volunteersubmission')),
            ],
            options={
                'verbose_name': 'Volunteer Project',
                'verbose_name_plural': 'Volunteer Projects',
                'unique_together': {('volunteer', 'project')},
            },
        ),
        migrations.CreateModel(
            name='VolunteerInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='careers.volunteersubmission')),
            ],
            options={
                'verbose_name': 'Volunteer Interest',
                'verbose_name_plural': 'Volunteer Interests',
                'unique_together': {('volunteer', 'interest')},
            },
        ),
    ]
