# Generated by Django 5.2.5 on 2025-09-25 07:54

import careers.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobbenefit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobbenefit',
            name='job',
        ),
        migrations.AlterUniqueTogether(
            name='jobqualification',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobqualification',
            name='job',
        ),
        migrations.AlterUniqueTogether(
            name='jobrequirement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobrequirement',
            name='job',
        ),
        migrations.AlterUniqueTogether(
            name='jobresponsibility',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobresponsibility',
            name='job',
        ),
        migrations.AlterUniqueTogether(
            name='volunteerinterest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='volunteerinterest',
            name='volunteer',
        ),
        migrations.AlterUniqueTogether(
            name='volunteerproject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='volunteerproject',
            name='volunteer',
        ),
        migrations.AlterUniqueTogether(
            name='volunteerskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='volunteerskill',
            name='volunteer',
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobopportunity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='volunteersubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='benefits',
            field=models.JSONField(default=list, help_text='List of benefits and perks'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='qualifications',
            field=models.JSONField(default=list, help_text='List of qualifications'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='requirements',
            field=models.JSONField(default=list, help_text='List of requirements'),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='responsibilities',
            field=models.JSONField(default=list, help_text='List of key responsibilities'),
        ),
        migrations.AddField(
            model_name='volunteersubmission',
            name='interests',
            field=models.JSONField(default=list, help_text='List of interests'),
        ),
        migrations.AddField(
            model_name='volunteersubmission',
            name='projects',
            field=models.JSONField(default=list, help_text='List of projects'),
        ),
        migrations.AddField(
            model_name='volunteersubmission',
            name='skills',
            field=models.JSONField(default=list, help_text='List of skills'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to=careers.models.job_application_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='contract_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Closed', 'Closed')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='work_arrangement',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='On-site', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteersubmission',
            name='availability',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['opportunity'], name='careers_job_opportu_478397_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status'], name='careers_job_status_3555c2_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['-created_at'], name='careers_job_created_6c06be_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['status'], name='careers_job_status_b09969_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['type'], name='careers_job_type_86140d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['department'], name='careers_job_departm_55f8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['location'], name='careers_job_locatio_2bfbef_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['-created_at'], name='careers_job_created_8622ce_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteersubmission',
            index=models.Index(fields=['status'], name='careers_vol_status_81316c_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteersubmission',
            index=models.Index(fields=['email'], name='careers_vol_email_789acc_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteersubmission',
            index=models.Index(fields=['-created_at'], name='careers_vol_created_4e4aba_idx'),
        ),
        migrations.DeleteModel(
            name='JobBenefit',
        ),
        migrations.DeleteModel(
            name='JobQualification',
        ),
        migrations.DeleteModel(
            name='JobRequirement',
        ),
        migrations.DeleteModel(
            name='JobResponsibility',
        ),
        migrations.DeleteModel(
            name='VolunteerInterest',
        ),
        migrations.DeleteModel(
            name='VolunteerProject',
        ),
        migrations.DeleteModel(
            name='VolunteerSkill',
        ),
    ]
