# Generated by Django 5.2.5 on 2025-09-26 20:24

import careers.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_jobbenefit_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='experience',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_file',
            field=models.FileField(blank=True, null=True, upload_to=careers.models.job_application_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
