# Generated by Django 5.2.5 on 2025-09-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalresource',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
