# Generated by Django 5.2.5 on 2025-09-03 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('excerpt', models.TextField(help_text='Brief description for listing pages')),
                ('abstract', models.TextField(blank=True, help_text='Detailed abstract', null=True)),
                ('full_content', models.TextField(blank=True, help_text='Full publication content', null=True)),
                ('type', models.CharField(choices=[('Research Paper', 'Research Paper'), ('Clinical Guidelines', 'Clinical Guidelines'), ('Educational Resource', 'Educational Resource'), ('Policy Brief', 'Policy Brief'), ('Research Report', 'Research Report')], default='Research Paper', max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('access_type', models.CharField(choices=[('Open Access', 'Open Access'), ('Free Access', 'Free Access'), ('Member Access', 'Member Access')], default='Open Access', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('journal', models.CharField(blank=True, max_length=200, null=True)),
                ('volume', models.CharField(blank=True, max_length=20, null=True)),
                ('issue', models.CharField(blank=True, max_length=20, null=True)),
                ('pages', models.CharField(blank=True, max_length=50, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('isbn', models.CharField(blank=True, max_length=17, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('authors', models.JSONField(default=list, help_text='List of author objects with name, credentials, affiliation, email')),
                ('target_audience', models.JSONField(default=list, help_text='List of target audiences')),
                ('tags', models.JSONField(default=list, help_text='List of tags')),
                ('keywords', models.JSONField(default=list, help_text='List of keywords for search')),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('citation_count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_records', to='publications.publication')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='publications.publication')),
            ],
            options={
                'unique_together': {('publication', 'ip_address')},
            },
        ),
    ]
