# Generated by Django 5.2.5 on 2025-08-16 09:05

import django.core.validators
import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gallery_items', models.PositiveIntegerField(default=0)),
                ('published_gallery_items', models.PositiveIntegerField(default=0)),
                ('total_stories', models.PositiveIntegerField(default=0)),
                ('published_stories', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Statistics',
                'verbose_name_plural': 'Gallery Statistics',
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('category', models.CharField(choices=[('conferences', 'Conferences'), ('training', 'Training'), ('community', 'Community'), ('events', 'Events'), ('outreach', 'Outreach'), ('medical', 'Medical'), ('education', 'Education')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Main image for photo items', null=True, upload_to=gallery.models.gallery_image_path)),
                ('video', models.FileField(blank=True, help_text='Video file for video items', null=True, upload_to=gallery.models.gallery_video_path)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image (auto-generated if not provided)', null=True, upload_to=gallery.models.gallery_thumbnail_path)),
                ('event_date', models.CharField(blank=True, help_text="Date when the event occurred (e.g., 'July 10, 2025')", max_length=100)),
                ('location', models.CharField(blank=True, help_text='Location where the event took place', max_length=200)),
                ('duration', models.CharField(blank=True, help_text="Duration for videos (e.g., '4:32')", max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_featured'], name='gallery_gal_status_cbdda8_idx'), models.Index(fields=['category', 'type'], name='gallery_gal_categor_abf682_idx'), models.Index(fields=['-created_at'], name='gallery_gal_created_60a839_idx')],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('patient_name', models.CharField(help_text="Patient's name (can be anonymized)", max_length=100)),
                ('age', models.PositiveIntegerField(help_text="Patient's age in years", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('condition', models.CharField(help_text='Medical condition (e.g., Epilepsy, Cerebral Palsy)', max_length=100)),
                ('story', models.TextField(help_text='The full story of transformation')),
                ('image', models.ImageField(help_text='Image associated with the story', upload_to=gallery.models.story_image_path)),
                ('location', models.CharField(blank=True, help_text='Location where the story took place', max_length=200)),
                ('story_date', models.CharField(blank=True, help_text="Date when the story occurred (e.g., 'June 15, 2025')", max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured story')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_featured'], name='gallery_sto_status_e90381_idx'), models.Index(fields=['condition'], name='gallery_sto_conditi_b7dcb2_idx'), models.Index(fields=['-created_at'], name='gallery_sto_created_1f61f4_idx')],
            },
        ),
    ]
