# Generated by Django 5.2.5 on 2025-09-12 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('content_id', models.PositiveIntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-downloaded_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='policy_mana_content_f82cf6_idx'), models.Index(fields=['downloaded_at'], name='policy_mana_downloa_573cc0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('content_id', models.PositiveIntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='policy_mana_content_6c38e0_idx'), models.Index(fields=['viewed_at'], name='policy_mana_viewed__c65b82_idx')],
                'unique_together': {('content_type', 'content_id', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='PolicyBelief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='Brief summary of the content')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_images/')),
                ('image_url', models.URLField(blank=True, help_text='Alternative to uploaded image', null=True)),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization and search')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('target_audience', models.JSONField(default=list, help_text='List of target audiences')),
                ('key_recommendations', models.JSONField(default=list, help_text='List of key policy recommendations')),
                ('region', models.JSONField(default=list, help_text='Regions this policy focuses on')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='policy_mana_status_388c45_idx'), models.Index(fields=['priority'], name='policy_mana_priorit_7fca34_idx'), models.Index(fields=['category'], name='policy_mana_categor_ec7a68_idx'), models.Index(fields=['-created_at'], name='policy_mana_created_1204f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PositionalStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='Brief summary of the content')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_images/')),
                ('image_url', models.URLField(blank=True, help_text='Alternative to uploaded image', null=True)),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization and search')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('key_points', models.JSONField(default=list, help_text='List of key points in the statement')),
                ('country_focus', models.JSONField(default=list, help_text='Countries this statement focuses on')),
                ('related_policies', models.JSONField(default=list, help_text='Related policy documents')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='policy_mana_status_e25523_idx'), models.Index(fields=['category'], name='policy_mana_categor_acbc2f_idx'), models.Index(fields=['page_count'], name='policy_mana_page_co_0835be_idx'), models.Index(fields=['-created_at'], name='policy_mana_created_09f023_idx')],
            },
        ),
    ]
