# Generated by Django 5.2.5 on 2025-09-24 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policybelief',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='policybelief',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='positionalstatement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='positionalstatement',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
