# Generated by Django 5.2.5 on 2025-08-19 11:05

import django.db.models.deletion
import webinars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(default='60 min', max_length=50)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Registration Open', 'Registration Open'), ('Live', 'Live'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planning', max_length=20)),
                ('type', models.CharField(choices=[('Live', 'Live'), ('Recorded', 'Recorded'), ('Hybrid', 'Hybrid')], default='Live', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('registration_count', models.PositiveIntegerField(default=0)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=webinars.models.webinar_image_path)),
                ('image_url', models.URLField(blank=True, help_text='External image URL or uploaded image path', null=True)),
                ('registration_link', models.URLField(blank=True)),
                ('recording_link', models.URLField(blank=True)),
                ('slides_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webinar',
                'verbose_name_plural': 'Webinars',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credentials', models.CharField(blank=True, max_length=150)),
                ('affiliation', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=webinars.models.speaker_image_path)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='webinars.webinar')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('registration_type', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Student', 'Student'), ('Professional', 'Professional')], default='Free', max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Free', 'Free'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='webinars.webinar')),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='WebinarObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='webinars.webinar')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebinarView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='webinars.webinar')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(max_length=100)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_audience', to='webinars.webinar')),
            ],
            options={
                'unique_together': {('webinar', 'audience')},
            },
        ),
        migrations.CreateModel(
            name='WebinarLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='webinars.webinar')),
            ],
            options={
                'unique_together': {('webinar', 'language')},
            },
        ),
        migrations.CreateModel(
            name='WebinarTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='webinars.webinar')),
            ],
            options={
                'unique_together': {('webinar', 'name')},
            },
        ),
    ]
