# Generated by Django 5.2.5 on 2025-08-27 15:56

import django.db.models.deletion
import patient_resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('full_description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Guide', 'Guide'), ('Video', 'Video'), ('Audio', 'Audio'), ('Checklist', 'Checklist'), ('App', 'App'), ('Website', 'Website'), ('Infographic', 'Infographic'), ('Handbook', 'Handbook')], default='Guide', max_length=20)),
                ('condition', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived'), ('Under Review', 'Under Review')], default='Draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=patient_resources.models.resource_image_path)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=patient_resources.models.resource_file_path)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('age_group', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('author', models.CharField(max_length=100)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_review_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Patient Resource',
                'verbose_name_plural': 'Patient Resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_records', to='patient_resources.patientresource')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='patient_resources.patientresource')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(max_length=100)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_audience', to='patient_resources.patientresource')),
            ],
            options={
                'unique_together': {('resource', 'audience')},
            },
        ),
        migrations.CreateModel(
            name='ResourceLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='patient_resources.patientresource')),
            ],
            options={
                'unique_together': {('resource', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='patient_resources.patientresource')),
            ],
            options={
                'unique_together': {('resource', 'name')},
            },
        ),
    ]
