# Generated by Django 5.2.5 on 2025-08-21 18:33

import abstracts.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('Clinical Research', 'Clinical Research'), ('Basic Science & Translational Research', 'Basic Science & Translational Research'), ('Healthcare Technology & Innovation', 'Healthcare Technology & Innovation'), ('Medical Education & Training', 'Medical Education & Training'), ('Public Health & Policy', 'Public Health & Policy'), ('Case Reports', 'Case Reports')], max_length=50)),
                ('presentation_preference', models.CharField(choices=[('Oral Presentation', 'Oral Presentation'), ('Poster Presentation', 'Poster Presentation'), ('E-Poster', 'E-Poster'), ('No Preference', 'No Preference')], default='No Preference', max_length=20)),
                ('keywords', models.JSONField(default=list)),
                ('background', models.TextField()),
                ('methods', models.TextField()),
                ('results', models.TextField()),
                ('conclusions', models.TextField()),
                ('conflict_of_interest', models.TextField()),
                ('status', models.CharField(choices=[('Under Review', 'Under Review'), ('Accepted', 'Accepted'), ('Revision Required', 'Revision Required'), ('Rejected', 'Rejected')], default='Under Review', max_length=20)),
                ('reviewer_comments', models.TextField(blank=True, null=True)),
                ('assigned_reviewer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('abstract_file', models.FileField(blank=True, null=True, upload_to=abstracts.models.abstract_file_path)),
                ('ethical_approval_file', models.FileField(blank=True, null=True, upload_to=abstracts.models.ethical_approval_path)),
                ('supplementary_files', models.FileField(blank=True, null=True, upload_to=abstracts.models.supplementary_file_path)),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('is_presenter', models.BooleanField(default=False)),
                ('is_corresponding', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='abstracts.abstract')),
            ],
            options={
                'ordering': ['order', 'last_name', 'first_name'],
            },
        ),
    ]
