# Generated by Django 5.2.5 on 2025-08-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2026)),
                ('abstract_submission_opens', models.CharField(default='January 15', help_text="Format: 'Month DD' or 'Month DD, YYYY'", max_length=100)),
                ('abstract_submission_deadline', models.CharField(default='April 30', help_text="Format: 'Month DD' or 'Month DD, YYYY'", max_length=100)),
                ('abstract_review_completion', models.CharField(default='June 15', help_text="Format: 'Month DD' or 'Month DD, YYYY'", max_length=100)),
                ('acceptance_notifications', models.CharField(default='July 1', help_text="Format: 'Month DD' or 'Month DD, YYYY'", max_length=100)),
                ('final_abstract_submission', models.CharField(default='August 15', help_text="Format: 'Month DD' or 'Month DD, YYYY'", max_length=100)),
                ('conference_presentation', models.CharField(default='March 15-17', help_text="Format: 'Month DD-DD' or 'Month DD-DD, YYYY'", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Only one set of dates can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Admin who created/updated these dates', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Important Dates',
                'verbose_name_plural': 'Important Dates',
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
