# Generated by Django 5.2.5 on 2025-09-04 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(help_text='Research abstract')),
                ('keywords', models.JSONField(default=list, help_text='List of keywords')),
                ('research_type', models.CharField(choices=[('Clinical Trial', 'Clinical Trial'), ('Observational Study', 'Observational Study'), ('Case Report', 'Case Report'), ('Case Series', 'Case Series'), ('Systematic Review', 'Systematic Review'), ('Meta-Analysis', 'Meta-Analysis'), ('Basic Science Research', 'Basic Science Research'), ('Epidemiological Study', 'Epidemiological Study'), ('Other', 'Other')], max_length=50)),
                ('category', models.CharField(choices=[('Pediatric Epilepsy', 'Pediatric Epilepsy'), ('Cerebral Palsy', 'Cerebral Palsy'), ('Neurodevelopmental Disorders', 'Neurodevelopmental Disorders'), ('Pediatric Stroke', 'Pediatric Stroke'), ('Infectious Diseases of CNS', 'Infectious Diseases of CNS'), ('Genetic Neurological Disorders', 'Genetic Neurological Disorders'), ('Neurooncology', 'Neurooncology'), ('Other', 'Other')], max_length=50)),
                ('study_design', models.CharField(blank=True, choices=[('Randomized Controlled Trial', 'Randomized Controlled Trial'), ('Cohort Study', 'Cohort Study'), ('Case-Control Study', 'Case-Control Study'), ('Cross-Sectional Study', 'Cross-Sectional Study'), ('Qualitative Study', 'Qualitative Study'), ('Mixed Methods', 'Mixed Methods'), ('Other', 'Other')], max_length=50, null=True)),
                ('participants', models.TextField(blank=True, help_text='Study participants description', null=True)),
                ('ethics_approval', models.BooleanField(default=False)),
                ('ethics_number', models.CharField(blank=True, max_length=100, null=True)),
                ('funding_source', models.CharField(blank=True, max_length=300, null=True)),
                ('conflict_of_interest', models.TextField(blank=True, null=True)),
                ('acknowledgments', models.TextField(blank=True, null=True)),
                ('target_journal', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Revision Required', 'Revision Required'), ('Accepted', 'Accepted'), ('Published', 'Published'), ('Rejected', 'Rejected')], default='Submitted', max_length=20)),
                ('manuscript_file', models.FileField(help_text='Main manuscript file', upload_to='research_papers/manuscripts/')),
                ('authors', models.JSONField(default=list, help_text='List of author objects with name, email, affiliation, isCorresponding')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('review_deadline', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(help_text='Brief description of the research project')),
                ('type', models.CharField(choices=[('Clinical Trial', 'Clinical Trial'), ('Observational Study', 'Observational Study'), ('Intervention Study', 'Intervention Study'), ('Epidemiological Study', 'Epidemiological Study'), ('Genetic Research', 'Genetic Research'), ('Cohort Study', 'Cohort Study'), ('Case-Control Study', 'Case-Control Study'), ('Systematic Review', 'Systematic Review'), ('Meta-Analysis', 'Meta-Analysis')], default='Clinical Trial', max_length=50)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Active', 'Active'), ('Recruiting', 'Recruiting'), ('Data Collection', 'Data Collection'), ('Analysis', 'Analysis'), ('Completed', 'Completed'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], default='Planning', max_length=20)),
                ('principal_investigator', models.CharField(max_length=200)),
                ('registration_number', models.CharField(blank=True, help_text='e.g., NCT12345678', max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('funding_source', models.CharField(blank=True, max_length=200, null=True)),
                ('funding_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('target_population', models.CharField(max_length=300)),
                ('sample_size', models.PositiveIntegerField(blank=True, null=True)),
                ('methodology', models.TextField(blank=True, help_text='Research methodology and approach', null=True)),
                ('ethics_approval', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='research_projects/images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('investigators', models.JSONField(default=list, help_text='List of investigator objects with name, role, affiliation, email')),
                ('institutions', models.JSONField(default=list, help_text='List of participating institutions')),
                ('objectives', models.JSONField(default=list, help_text='List of research objectives')),
                ('keywords', models.JSONField(default=list, help_text='List of keywords for search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPaperComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_name', models.CharField(max_length=200)),
                ('commenter_email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comment visible only to reviewers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='research_projects.researchpaper')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPaperFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='research_papers/supplementary/')),
                ('file_type', models.CharField(choices=[('supplementary', 'Supplementary Material'), ('figure', 'Figure'), ('dataset', 'Dataset'), ('appendix', 'Appendix'), ('other', 'Other')], default='supplementary', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('research_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_files', to='research_projects.researchpaper')),
            ],
            options={
                'ordering': ['file_type', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPaperReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=200)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('review_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('recommendation', models.CharField(blank=True, choices=[('Accept', 'Accept'), ('Minor Revisions', 'Minor Revisions'), ('Major Revisions', 'Major Revisions'), ('Reject', 'Reject')], max_length=20, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('research_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='research_projects.researchpaper')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='research_project',
            field=models.ForeignKey(blank=True, help_text='Link to related research project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_papers', to='research_projects.researchproject'),
        ),
        migrations.CreateModel(
            name='ResearchProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('update_type', models.CharField(choices=[('Milestone', 'Milestone'), ('Status Change', 'Status Change'), ('Publication', 'Publication'), ('General Update', 'General Update')], default='General Update', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='research_projects.researchproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProjectView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('research_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='research_projects.researchproject')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('research_project', 'ip_address')},
            },
        ),
    ]
