# Generated by Django 5.2.5 on 2025-09-04 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(help_text='Brief description of the research project')),
                ('type', models.CharField(choices=[('Clinical Trial', 'Clinical Trial'), ('Observational Study', 'Observational Study'), ('Intervention Study', 'Intervention Study'), ('Epidemiological Study', 'Epidemiological Study'), ('Genetic Research', 'Genetic Research'), ('Cohort Study', 'Cohort Study'), ('Case-Control Study', 'Case-Control Study'), ('Systematic Review', 'Systematic Review'), ('Meta-Analysis', 'Meta-Analysis')], default='Clinical Trial', max_length=50)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Active', 'Active'), ('Recruiting', 'Recruiting'), ('Data Collection', 'Data Collection'), ('Analysis', 'Analysis'), ('Completed', 'Completed'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], default='Planning', max_length=20)),
                ('principal_investigator', models.CharField(max_length=200)),
                ('registration_number', models.CharField(blank=True, help_text='e.g., NCT12345678', max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('funding_source', models.CharField(blank=True, max_length=200, null=True)),
                ('funding_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('target_population', models.CharField(max_length=300)),
                ('sample_size', models.PositiveIntegerField(blank=True, null=True)),
                ('methodology', models.TextField(blank=True, help_text='Research methodology and approach', null=True)),
                ('ethics_approval', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='research_projects/images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('investigators', models.JSONField(default=list, help_text='List of investigator objects with name, role, affiliation, email')),
                ('institutions', models.JSONField(default=list, help_text='List of participating institutions')),
                ('objectives', models.JSONField(default=list, help_text='List of research objectives')),
                ('keywords', models.JSONField(default=list, help_text='List of keywords for search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('update_type', models.CharField(choices=[('Milestone', 'Milestone'), ('Status Change', 'Status Change'), ('Publication', 'Publication'), ('General Update', 'General Update')], default='General Update', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='research_projects.researchproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProjectView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('research_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='research_projects.researchproject')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('research_project', 'ip_address')},
            },
        ),
    ]
