# Generated by Django 5.2.5 on 2025-09-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='experience',
            field=models.CharField(choices=[('Less than 1 year', 'Less than 1 year'), ('1-2 years', '1-2 years'), ('3-5 years', '3-5 years'), ('6-10 years', '6-10 years'), ('11-15 years', '11-15 years'), ('More than 15 years', 'More than 15 years')], default='1-2 years', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional: External image URL if no file uploaded', null=True),
        ),
    ]
