# Generated by Django 5.2.5 on 2025-09-26 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_programs', '0002_alter_registration_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('free', 'Free'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TrainingProgramPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stripe_checkout_session_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_type', models.CharField(choices=[('registration', 'Registration Fee'), ('late_fee', 'Late Registration Fee')], default='registration', max_length=20)),
                ('registration_type', models.CharField(default='regular', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='training_programs.trainingprogram')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='training_programs.registration')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['program', 'status'], name='training_pr_program_baf3de_idx'), models.Index(fields=['stripe_checkout_session_id'], name='training_pr_stripe__280723_idx')],
            },
        ),
    ]
