# Generated by Django 5.2.5 on 2025-08-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='upgrade_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
