# Generated by Django 5.2.5 on 2025-08-20 18:10

import awards.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('criteria', models.TextField(blank=True, help_text='Key criteria for this award')),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Award Categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AwardNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(max_length=200)),
                ('nominee_email', models.EmailField(blank=True, max_length=254)),
                ('nominee_institution', models.CharField(max_length=300)),
                ('nominee_location', models.CharField(blank=True, max_length=200)),
                ('nominee_specialty', models.CharField(blank=True, max_length=200)),
                ('nominator_name', models.CharField(max_length=200)),
                ('nominator_email', models.EmailField(max_length=254)),
                ('nominator_relationship', models.CharField(blank=True, max_length=200)),
                ('achievement_summary', models.TextField()),
                ('additional_info', models.TextField(blank=True)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='nominations/documents/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=12)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('suggested', 'From Suggested Nominee'), ('new', 'New Nomination')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='awards.awardcategory')),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='AwardWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=200)),
                ('achievement', models.TextField()),
                ('year', models.PositiveIntegerField(default=2025)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Archived', 'Archived')], default='Active', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=awards.models.award_image_path)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='awards.awardcategory')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=300)),
                ('specialty', models.CharField(max_length=200)),
                ('achievement', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=awards.models.nominee_image_path)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Winner', 'Winner')], default='Pending', max_length=10)),
                ('suggested_by', models.CharField(blank=True, max_length=200)),
                ('suggested_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('admin', 'Admin Added'), ('suggested', 'Suggested Nominee'), ('new', 'New Nomination'), ('nomination', 'Public Nomination')], default='admin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='awards.awardcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
