# Generated by Django 5.2.5 on 2025-08-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardnomination',
            name='source',
            field=models.CharField(choices=[('suggested', 'From Suggested Nominee')], default='suggested', max_length=10),
        ),
        migrations.AlterField(
            model_name='awardnomination',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=12),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin Added'), ('suggested', 'Suggested Nominee')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Winner', 'Winner')], default='Approved', max_length=10),
        ),
    ]
