# Generated by Django 5.2.5 on 2025-08-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin Added'), ('nomination', 'Public Nomination')], default='admin', max_length=20),
        ),
    ]
