# Generated by Django 5.2.5 on 2025-08-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_nominee_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardnomination',
            name='source',
            field=models.CharField(choices=[('suggested', 'From Suggested Nominee'), ('new', 'New Nomination')], default='new', max_length=10),
        ),
    ]
