# Generated by Django 5.2.5 on 2025-08-22 12:44

import django.db.models.deletion
import workshops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('institution', models.CharField(max_length=200)),
                ('project_lead', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('commitment_level', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Needs Info', 'Needs Info')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collaboration Submission',
                'verbose_name_plural': 'Collaboration Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(default='3 hours', max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(choices=[('Online', 'Online'), ('In-Person', 'In-Person'), ('Hybrid', 'Hybrid')], default='In-Person', max_length=10)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Registration Open', 'Registration Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planning', max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=workshops.models.workshop_image_path)),
                ('image_url', models.URLField(blank=True, help_text='External image URL or uploaded image path', null=True)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('registered', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_needed', to='workshops.collaborationsubmission')),
            ],
            options={
                'unique_together': {('collaboration', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='WorkshopMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=200)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='workshops.workshop')),
            ],
            options={
                'unique_together': {('workshop', 'material')},
            },
        ),
        migrations.CreateModel(
            name='WorkshopPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.CharField(max_length=200)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='workshops.workshop')),
            ],
            options={
                'unique_together': {('workshop', 'prerequisite')},
            },
        ),
    ]
