# Generated by Django 5.2.5 on 2025-09-11 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
                ('journal', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Brief summary of the article')),
                ('abstract', models.TextField(blank=True, help_text='Full abstract (optional)', null=True)),
                ('relevance', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('study_type', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=300)),
                ('access', models.CharField(choices=[('Open', 'Open Access'), ('Subscription', 'Subscription Required')], default='Open', max_length=20)),
                ('commentary', models.TextField(blank=True, help_text='ACNA commentary on the article', null=True)),
                ('key_findings', models.JSONField(default=list, help_text='List of key findings')),
                ('country_focus', models.JSONField(default=list, help_text='Countries the study focuses on')),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization and search')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='journal_wat_status_7d3a2f_idx'), models.Index(fields=['relevance'], name='journal_wat_relevan_79c3c9_idx'), models.Index(fields=['study_type'], name='journal_wat_study_t_fd0ac7_idx'), models.Index(fields=['-created_at'], name='journal_wat_created_4283d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='JournalArticleDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='journal_watch.journalarticle')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='journal_watch.journalarticle')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('article', 'ip_address')},
            },
        ),
    ]
