# Generated by Django 5.2.5 on 2025-09-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_watch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalarticle',
            name='access',
        ),
    ]
