# Generated by Django 5.2.5 on 2025-08-17 07:18

import django.db.models.deletion
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('type', models.CharField(choices=[('News Article', 'News Article'), ('Press Release', 'Press Release'), ('Announcement', 'Announcement'), ('Research Update', 'Research Update')], default='News Article', max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('read_time', models.CharField(default='5 min', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=news.models.news_image_path)),
                ('image_url', models.URLField(blank=True)),
                ('introduction', models.TextField()),
                ('conclusion', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('author_title', models.CharField(blank=True, max_length=150)),
                ('author_organization', models.CharField(blank=True, max_length=150)),
                ('author_bio', models.TextField(blank=True)),
                ('author_image_url', models.URLField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Item',
                'verbose_name_plural': 'News Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='news.newsitem')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
