# Generated by Django 5.2.5 on 2025-08-17 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
