# Generated by Django 5.2.5 on 2025-08-17 10:49

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.author_image_path),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='author_image_url',
            field=models.URLField(blank=True, help_text='External author image URL or uploaded image path', null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL or uploaded image path', null=True),
        ),
    ]
