# Generated by Django 5.2.5 on 2025-08-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsitem_author_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='sections',
            field=models.TextField(blank=True, help_text='Stores sections as JSON'),
        ),
    ]
